[template]
src = "credentials.conf.tmpl"
dest = "/app/properties/credentials.properties"
keys = [
    "/spring/datasource/url",
    "/spring/datasource/username",
    "/spring/datasource/password"
]